### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by herpiko** [abraincode/backend-senada#1]
@dhimasanb scopenya apa saja?

**Comment by dhimasanb** [comment]
sebentar yaa.. lagi dibikin 😆

**Comment by dhimasanb** [comment]
@herpiko nih bang https://github.com/abraincode/backend-senada/projects 😆

**Comment by dhimasanb** [comment]
tolong koreksi klo ada yg salah dan tambahin yg kurang bang.. hehe

**Comment by herpiko** [comment]
@dhimasanb tiket-tiket yang baru saya buat itu contoh garis besar skupnya, mewakili data-data yang dikelola di situs. Nanti perlu didetilin lagi.
